type: "transformation"
version: "1.0"
pipeline:
  components:
    Today's Date:
      type: "fixed-flow"
      parameters:
        componentName: "Today's Date"
        columns:
        - - "last_updated"
          - "DATE"
          - ""
          - ""
        values:
        - - "${proj_today_date}"
    Shoe Specifications:
      type: "table-input"
      parameters:
        componentName: "Shoe Specifications"
        database: "[Environment Default]"
        schema: "[Environment Default]"
        targetTable: "CHARLIES_SHOE_EMPORIUM_SHOE_SPECIFICATIONS"
        columnNames:
        - "PRODUCT_NAME"
        - "PRIMARY_COLOR"
        - "SECONDARY_COLOR"
        - "PRODUCT_LINE"
        - "COMFORT"
        - "RESPONSIVENESS"
        - "WEIGHT_OZ"
        - "CUSHIONING"
        - "BREATHABILITY"
        timeOffset:
    Join:
      type: "join"
      sources:
      - "Shoe Specifications"
      - "Today's Date"
      - "Filter <= Today Date"
      - "charlies_shoe_emporium_store_locations_FL"
      parameters:
        componentName: "Join"
        mainTable: "Filter <= Today Date"
        mainTableAlias: "sales"
        joins:
        - - "charlies_shoe_emporium_store_locations_FL"
          - "stores"
          - "Left"
        - - "Today's Date"
          - "date"
          - "Left"
        - - "Shoe Specifications"
          - "shoes"
          - "Left"
        joinExpressions:
        - - "\"sales\".\"STORE_ID\" = \"stores\".\"STORE_ID\""
          - "sales_Left_stores"
        - - "1 = 1"
          - "sales_Left_date"
        - - "\"sales\".\"PRODUCT_NAME\" = \"shoes\".\"PRODUCT_NAME\""
          - "sales_Left_shoes"
        columnMappings:
        - - "date.last_updated"
          - "LAST_UPDATED"
        - - "stores.LOCATION_NAME"
          - "STORE_LOCATION"
        - - "sales.TRANSACTION_ID"
          - "TRANSACTION_ID"
        - - "sales.TRANSACTION_DATE"
          - "TRANSACTION_DATE"
        - - "sales.PRODUCT_NAME"
          - "PRODUCT_NAME"
        - - "sales.SALE_INDICATOR"
          - "SALE_INDICATOR"
        - - "sales.PRODUCT_PRICE"
          - "PRODUCT_PRICE"
        - - "sales.REVIEW_INDICATOR"
          - "REVIEW_INDICATOR"
        - - "sales.REVIEW"
          - "REVIEW"
        - - "shoes.PRIMARY_COLOR"
          - "PRIMARY_COLOR"
        - - "shoes.SECONDARY_COLOR"
          - "SECONDARY_COLAR"
        - - "shoes.PRODUCT_LINE"
          - "PRODUCT_LINE"
        - - "shoes.COMFORT"
          - "COMFORT"
        - - "shoes.RESPONSIVENESS"
          - "RESPONSIVENESS"
        - - "shoes.WEIGHT_OZ"
          - "WEIGHT_OZ"
        - - "shoes.CUSHIONING"
          - "CUSHIONING"
        - - "shoes.BREATHABILITY"
          - "BREATHABILITY"
    Filter <= Today Date:
      type: "filter"
      sources:
      - "raw_charlies_shoe_emporium_sales_FL"
      parameters:
        componentName: "Filter <= Today Date"
        filterConditions:
        - - "TRANSACTION_DATE"
          - "Is"
          - "Less than or equal to"
          - "${proj_today_date}"
        combineCondition: "And"
    raw_charlies_shoe_emporium_sales_FL:
      type: "table-input"
      parameters:
        componentName: "raw_charlies_shoe_emporium_sales_FL"
        database: "[Environment Default]"
        schema: "[Environment Default]"
        targetTable: "RAW_CHARLIES_SHOE_EMPORIUM_SALES_FL"
        columnNames:
        - "TRANSACTION_ID"
        - "TRANSACTION_DATE"
        - "PRODUCT_NAME"
        - "SALE_INDICATOR"
        - "STORE_ID"
        - "REVIEW_INDICATOR"
        - "PRODUCT_ID"
        - "PRODUCT_PRICE"
        - "REVIEW"
        timeOffset:
    charlies_shoe_emporium_store_locations_FL:
      type: "table-input"
      parameters:
        componentName: "charlies_shoe_emporium_store_locations_FL"
        database: "[Environment Default]"
        schema: "[Environment Default]"
        targetTable: "CHARLIES_SHOE_EMPORIUM_STORE_LOCATIONS_FL"
        columnNames:
        - "STORE_ID"
        - "LOCATION_NAME"
        timeOffset:
    Rewrite Table:
      type: "rewrite-table"
      sources:
      - "Join"
      parameters:
        componentName: "Rewrite Table"
        warehouse: "[Environment Default]"
        database: "[Environment Default]"
        schema: "[Environment Default]"
        targetTable: "SRC_CHARLIES_SHOE_EMPORIUM_SALES"
        orderBy:
    src_charlies_shoe_emporium_sales:
      type: "table-input"
      parameters:
        componentName: "src_charlies_shoe_emporium_sales"
        database: "[Environment Default]"
        schema: "[Environment Default]"
        targetTable: "SRC_CHARLIES_SHOE_EMPORIUM_SALES"
        columnNames:
        - "LAST_UPDATED"
        - "STORE_LOCATION"
        - "TRANSACTION_ID"
        - "TRANSACTION_DATE"
        - "PRODUCT_NAME"
        - "SALE_INDICATOR"
        - "PRODUCT_PRICE"
        - "REVIEW_INDICATOR"
        - "REVIEW"
        - "PRIMARY_COLOR"
        - "SECONDARY_COLAR"
        - "PRODUCT_LINE"
        - "COMFORT"
        - "RESPONSIVENESS"
        - "WEIGHT_OZ"
        - "CUSHIONING"
        - "BREATHABILITY"
        timeOffset:
design:
  components:
    Today's Date:
      position:
        x: 260
        "y": 340
      tempMetlId: 3
    Shoe Specifications:
      position:
        x: 260
        "y": 440
      tempMetlId: 4
    Join:
      position:
        x: 550
        "y": 230
      tempMetlId: 5
    Filter <= Today Date:
      position:
        x: 410
        "y": 120
      tempMetlId: 6
    raw_charlies_shoe_emporium_sales_FL:
      position:
        x: 260
        "y": 120
      tempMetlId: 7
    charlies_shoe_emporium_store_locations_FL:
      position:
        x: 260
        "y": 230
      tempMetlId: 8
    Rewrite Table:
      position:
        x: 700
        "y": 230
      tempMetlId: 9
    src_charlies_shoe_emporium_sales:
      position:
        x: 860
        "y": 230
      tempMetlId: 10
