type: "transformation"
version: "1.0"
pipeline:
  components:
    Aggregate - Sentiment by Shoe Model:
      type: "aggregate"
      sources:
      - "Sentiment Analysis"
      parameters:
        componentName: "Aggregate - Sentiment by Shoe Model"
        groupings:
        - "PRODUCT_NAME"
        aggregations:
        - - "sentiment_REVIEW"
          - "Average"
        groupingType: "Group By"
    Rewrite Table:
      type: "rewrite-table"
      sources:
      - "Aggregate - Sentiment by Shoe Model"
      parameters:
        componentName: "Rewrite Table"
        warehouse: "[Environment Default]"
        database: "[Environment Default]"
        schema: "[Environment Default]"
        targetTable: "CHARLIES_SENTIMENT_BY_SHOE"
        orderBy:
    SRC_CHARLIES_SHOE_EMPORIUM_SALES:
      type: "table-input"
      parameters:
        componentName: "SRC_CHARLIES_SHOE_EMPORIUM_SALES"
        database: "[Environment Default]"
        schema: "[Environment Default]"
        targetTable: "SRC_CHARLIES_SHOE_EMPORIUM_SALES"
        columnNames:
        - "TRANSACTION_ID"
        - "PRODUCT_NAME"
        - "REVIEW_INDICATOR"
        - "REVIEW"
        timeOffset:
    Filter Reviews:
      type: "filter"
      sources:
      - "SRC_CHARLIES_SHOE_EMPORIUM_SALES"
      parameters:
        componentName: "Filter Reviews"
        filterConditions:
        - - "REVIEW_INDICATOR"
          - "Is"
          - "Equal to"
          - "true"
        combineCondition: "And"
    Sentiment Analysis:
      type: "cortex-sentiment"
      sources:
      - "Filter Reviews"
      parameters:
        componentName: "Sentiment Analysis"
        columns:
        - "REVIEW"
        includeInputColumns: "Yes"
design:
  components:
    Aggregate - Sentiment by Shoe Model:
      position:
        x: 180
        "y": 110
      tempMetlId: 2
    Rewrite Table:
      position:
        x: 320
        "y": 110
      tempMetlId: 3
    SRC_CHARLIES_SHOE_EMPORIUM_SALES:
      position:
        x: -290
        "y": 110
      tempMetlId: 4
    Filter Reviews:
      position:
        x: -130
        "y": 110
      tempMetlId: 6
    Sentiment Analysis:
      position:
        x: 30
        "y": 110
      tempMetlId: 7
